# Generated by Django 4.2 on 2023-04-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_id',
        ),
    ]
