# Generated by Django 4.2 on 2023-04-22 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
    ]
